# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: uv sync --frozen --all-packages
    name: uv sync --frozen --all-packages
    entry: uv sync --frozen --all-packages
    language: system
    pass_filenames: false
    require_serial: true
    always_run: true

  - id: uv run ruff format --check
    name: uv run ruff format --check
    entry: uv run ruff format --check
    language: system
    pass_filenames: false
    always_run: true

  - id: uv run ruff check
    name: uv run ruff check
    entry: uv run ruff check
    language: system
    pass_filenames: false
    always_run: true
