vectordb:
  type: qdrant

search:
  topk: 10
  queries_file: benchmark/queries.txt

update:
  add_count: 50
  delete_count: 30

compute_recall: false

baseline:
  results: "baseline_results.npy"
  results_post_update: "baseline_results_post_update.npy"

embedding_model:
  model_id: openai/clip-vit-base-patch32